"""B0-Delta: matched B0 duration experiment with an EMA-teacher residual target.

Only the SSL prediction target differs from B0:
    B0:       P(S(x_s), s, a, delta) -> T(x_t)
    B0-Delta: P(S(x_s), s, a, delta) -> T(x_t) - T(x_s)

Here x_s is the more-degraded source and x_t is the adjacent less-degraded
target generated by the unchanged B0 degradation sampler. The student, EMA
teacher, B0 predictor, optimizer/schedules, VICReg control, validation monitor,
checkpoint rule, data, and 300-epoch horizon are intentionally matched to B0.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import torch
import torch.nn.functional as F

from .data import build_ssl_loader
from .degradations import degrade_batch, sample_adjacent_transitions
from .losses import b0_loss
from .models import update_ema
from .monitor import SSLRepresentationMonitor, improves_macro_f1
from .training import (
    _cosine,
    _endpoints,
    _learning_rate,
    _make_optimizer,
    _save_final_student,
    _weight_decay,
    build_b0_models,
)
from .utils import atomic_json_dump, plot_history, seed_everything, write_csv


EXPECTED_MODEL = {
    "image_size": 256,
    "patch_size": 32,
    "hidden_size": 768,
    "predictor_dim": 384,
    "predictor_depth": 2,
    "predictor_heads": 6,
    "predictor_mlp_ratio": 4,
    "dropout": 0.0,
}

EXPECTED_TRAIN = {
    "epochs": 300,
    "batch_size": 128,
    "effective_batch_size": 128,
    "num_workers": 8,
    "cache_in_ram": True,
    "learning_rate": 1e-4,
    "minimum_learning_rate": 1e-6,
    "weight_decay": 0.04,
    "final_weight_decay": 0.40,
    "warmup_fraction": 0.10,
    "lambda_reg": 0.10,
    "covariance_weight": 0.04,
    "variance_target": 1.0,
    "ema_start": 0.996,
    "gradient_clip_norm": 5.0,
    "bf16": True,
    "compile": False,
    "resume": None,
}

EXPECTED_MONITOR = {
    "enabled": True,
    "batch_size": 256,
    "num_workers": 8,
    "cache_in_ram": True,
    "evaluation_interval_epochs": 10,
    "knn_k": 20,
    "knn_temperature": 0.07,
    "linear_lbfgs_max_iter": 100,
    "near_constant_std_threshold": 0.05,
    "minimum_delta_macro_f1": 0.005,
}


def validate_config(config: dict[str, Any]) -> None:
    """Fail closed if the experiment drifts from the completed B0 protocol."""
    if int(config["seed"]) != 20260903:
        raise ValueError("B0-Delta must use the matched B0 seed 20260903")
    if config["model"] != EXPECTED_MODEL:
        raise ValueError("B0-Delta model settings must exactly match B0")
    train = config["train"]
    mismatched_train = {
        key: (train.get(key), value)
        for key, value in EXPECTED_TRAIN.items()
        if train.get(key) != value
    }
    if mismatched_train:
        raise ValueError(f"B0-Delta train settings differ from B0: {mismatched_train}")
    monitor = config["monitor"]
    mismatched_monitor = {
        key: (monitor.get(key), value)
        for key, value in EXPECTED_MONITOR.items()
        if monitor.get(key) != value
    }
    if mismatched_monitor:
        raise ValueError(f"B0-Delta monitor settings differ from B0: {mismatched_monitor}")
    if Path(config["output_dir"]).name != "b0_delta_duration_pilot":
        raise ValueError("B0-Delta output_dir must end in b0_delta_duration_pilot")


def teacher_delta_target(
    teacher_source: torch.Tensor,
    teacher_target: torch.Tensor,
) -> torch.Tensor:
    """Return the less-degraded minus more-degraded teacher representation in FP32."""
    if teacher_source.shape != teacher_target.shape:
        raise ValueError("Teacher source and target tensors must have identical shapes")
    return (teacher_target.float() - teacher_source.float()).detach()


@torch.no_grad()
def _batch_residual_diagnostics(
    prediction: torch.Tensor,
    target_delta: torch.Tensor,
) -> dict[str, torch.Tensor]:
    pred = prediction.float()
    target = target_delta.float()
    per_example_prediction = F.smooth_l1_loss(pred, target, reduction="none").mean(dim=(1, 2))
    per_example_zero = F.smooth_l1_loss(torch.zeros_like(target), target, reduction="none").mean(dim=(1, 2))
    per_example_cosine = F.cosine_similarity(pred.flatten(1), target.flatten(1), dim=1)
    return {
        "prediction": per_example_prediction,
        "zero_prediction": per_example_zero,
        "cosine": per_example_cosine,
        "target_squared_sum": target.square().sum(),
        "target_elements": torch.tensor(target.numel(), device=target.device, dtype=torch.long),
    }


def run_b0_delta_pretraining(config: dict[str, Any]) -> dict[str, Any]:
    if not torch.cuda.is_available():
        raise RuntimeError("B0-Delta pretraining requires CUDA")
    validate_config(config)

    seed_everything(int(config["seed"]))
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    device = torch.device("cuda")
    train = config["train"]
    output_dir = Path(config["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    if (output_dir / "pretrain_metrics.csv").exists():
        raise FileExistsError(
            f"Refusing to overwrite an existing B0-Delta duration run: {output_dir}"
        )
    atomic_json_dump(config, output_dir / "resolved_config.json")

    endpoints = _endpoints(config["endpoints_json"])
    loader, _ = build_ssl_loader(
        config["data_root"],
        batch_size=int(train["batch_size"]),
        num_workers=int(train["num_workers"]),
        cache_in_ram=bool(train["cache_in_ram"]),
    )
    if len(loader.dataset) != 7901:
        raise RuntimeError(f"Expected 7,901 unlabeled SSL images, got {len(loader.dataset)}")

    student, teacher, predictor = build_b0_models(config, device)
    trainable = list(student.parameters()) + list(predictor.parameters())
    optimizer = _make_optimizer(
        trainable,
        float(train["learning_rate"]),
        float(train["weight_decay"]),
    )

    epochs = int(train["epochs"])
    total_steps = epochs * len(loader)  # effective batch == physical batch == 128
    global_step = 0
    history: list[dict[str, float]] = []

    run_started = time.perf_counter()
    monitor_config = config["monitor"]
    monitor = SSLRepresentationMonitor(
        monitor_config,
        data_root=config["data_root"],
        output_dir=output_dir,
        seed=int(config["seed"]),
        device=device,
    )
    baseline = monitor.evaluate(student, epoch=0)
    best_monitor_score = float(baseline["linear_val_macro_f1"])
    best_epoch = 0
    _save_final_student(
        output_dir / "checkpoints" / "best.pt",
        student=student,
        config=config,
        epoch=0,
        history=history,
        selection={
            "metric": "validation_linear_macro_f1",
            "value": best_monitor_score,
            "minimum_delta": float(monitor_config["minimum_delta_macro_f1"]),
            "selection_split": "validation",
            "transductive_ssl": True,
        },
    )
    print(json.dumps({"monitor": baseline}, sort_keys=True), flush=True)

    for epoch in range(epochs):
        student.train()
        predictor.train()
        teacher.eval()
        torch.cuda.reset_peak_memory_stats()

        totals = {
            name: 0.0
            for name in (
                "total",
                "prediction",
                "regularizer",
                "variance",
                "covariance",
                "embedding_std",
                "zero_prediction",
                "residual_cosine",
            )
        }
        target_delta_squared_sum = 0.0
        target_delta_elements = 0

        transition_prediction = {
            f"{family}_{source:03d}_to_{target:03d}": [0.0, 0]
            for family in ("defocus", "resolution")
            for source, target in ((100, 75), (75, 50), (50, 25), (25, 0))
        }
        transition_zero = {
            key: [0.0, 0]
            for key in transition_prediction
        }

        seen = 0
        epoch_started = time.perf_counter()
        optimizer.zero_grad(set_to_none=True)

        for batch_index, uint8_images in enumerate(loader):
            images = uint8_images.to(
                device=device,
                dtype=torch.float32,
                non_blocking=True,
            ).div_(255.0)

            actions, source_severity, target_severity, delta = sample_adjacent_transitions(
                images.shape[0], device
            )
            expected_step = torch.full_like(source_severity, 0.25)
            if not torch.equal(source_severity - target_severity, expected_step):
                raise RuntimeError("B0-Delta received a non-adjacent degradation transition")
            if not torch.equal(delta, -expected_step):
                raise RuntimeError("B0-Delta requires target-source delta=-0.25")

            source_images = degrade_batch(images, actions, source_severity, endpoints)
            target_images = degrade_batch(images, actions, target_severity, endpoints)

            with torch.autocast(
                device_type="cuda",
                dtype=torch.bfloat16,
                enabled=bool(train["bf16"]),
            ):
                student_tokens = student(source_images)
                prediction = predictor(
                    student_tokens,
                    source_severity,
                    actions,
                    delta,
                )
                with torch.no_grad():
                    teacher_source = teacher(source_images)
                    teacher_target = teacher(target_images)

            target_delta = teacher_delta_target(teacher_source, teacher_target)
            losses = b0_loss(
                prediction,
                target_delta,
                student_tokens,
                lambda_reg=float(train["lambda_reg"]),
                covariance_weight=float(train["covariance_weight"]),
                variance_target=float(train["variance_target"]),
            )
            if not torch.isfinite(losses["total"]):
                raise FloatingPointError(
                    f"Non-finite B0-Delta loss at epoch={epoch + 1}, batch={batch_index}"
                )

            losses["total"].backward()
            gradient_norm = torch.nn.utils.clip_grad_norm_(
                trainable,
                float(train["gradient_clip_norm"]),
            )
            if not torch.isfinite(gradient_norm):
                raise FloatingPointError("Non-finite B0-Delta gradient norm")

            learning_rate = _learning_rate(train, global_step, total_steps)
            weight_decay = _weight_decay(train, global_step, total_steps)
            for group in optimizer.param_groups:
                group["lr"] = learning_rate
                group["weight_decay"] = weight_decay
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

            momentum = _cosine(
                float(train["ema_start"]),
                1.0,
                global_step,
                total_steps,
            )
            update_ema(student, teacher, momentum)
            global_step += 1

            diagnostics = _batch_residual_diagnostics(prediction, target_delta)
            count = images.shape[0]
            seen += count
            for name in ("total", "prediction", "regularizer", "variance", "covariance", "embedding_std"):
                totals[name] += float(losses[name].detach()) * count
            totals["zero_prediction"] += float(diagnostics["zero_prediction"].sum())
            totals["residual_cosine"] += float(diagnostics["cosine"].sum())
            target_delta_squared_sum += float(diagnostics["target_squared_sum"])
            target_delta_elements += int(diagnostics["target_elements"])

            per_example_prediction = diagnostics["prediction"]
            per_example_zero = diagnostics["zero_prediction"]
            for action, family in ((0, "defocus"), (1, "resolution")):
                action_mask = actions == action
                if not torch.any(action_mask):
                    continue
                source_values = source_severity[action_mask]
                for source_anchor in (1.0, 0.75, 0.5, 0.25):
                    anchor_mask = action_mask.clone()
                    anchor_mask[action_mask] = torch.isclose(
                        source_values,
                        torch.tensor(source_anchor, device=device),
                    )
                    if not torch.any(anchor_mask):
                        continue
                    target_anchor = source_anchor - 0.25
                    key = (
                        f"{family}_{int(round(source_anchor * 100)):03d}"
                        f"_to_{int(round(target_anchor * 100)):03d}"
                    )
                    pred_values = per_example_prediction[anchor_mask]
                    zero_values = per_example_zero[anchor_mask]
                    transition_prediction[key][0] += float(pred_values.sum())
                    transition_prediction[key][1] += int(pred_values.numel())
                    transition_zero[key][0] += float(zero_values.sum())
                    transition_zero[key][1] += int(zero_values.numel())

        if seen != 7901:
            raise RuntimeError(f"Expected 7,901 samples per epoch, saw {seen}")

        seconds = time.perf_counter() - epoch_started
        row: dict[str, float] = {
            "epoch": epoch + 1,
            **{name: value / seen for name, value in totals.items()},
            "learning_rate": float(optimizer.param_groups[0]["lr"]),
            "weight_decay": float(optimizer.param_groups[0]["weight_decay"]),
            "ema_momentum": float(
                _cosine(
                    float(train["ema_start"]),
                    1.0,
                    max(0, global_step - 1),
                    total_steps,
                )
            ),
            "seconds": seconds,
            "samples_per_second": seen / seconds,
            "peak_gpu_memory_gib": torch.cuda.max_memory_allocated() / 2**30,
            "target_delta_rms": (
                target_delta_squared_sum / max(1, target_delta_elements)
            ) ** 0.5,
        }
        row["residual_skill"] = 1.0 - row["prediction"] / max(
            row["zero_prediction"], 1e-12
        )

        for key, (pred_sum, pred_count) in transition_prediction.items():
            zero_sum, zero_count = transition_zero[key]
            if pred_count != zero_count:
                raise RuntimeError(f"Transition diagnostic count mismatch for {key}")
            pred_mean = pred_sum / pred_count if pred_count else float("nan")
            zero_mean = zero_sum / zero_count if zero_count else float("nan")
            row[f"prediction_{key}"] = pred_mean
            row[f"zero_prediction_{key}"] = zero_mean
            row[f"residual_skill_{key}"] = (
                1.0 - pred_mean / max(zero_mean, 1e-12)
                if pred_count
                else float("nan")
            )

        history.append(row)
        write_csv(history, output_dir / "pretrain_metrics.csv")
        print(json.dumps(row, sort_keys=True), flush=True)

        if (epoch + 1) % int(monitor_config["evaluation_interval_epochs"]) == 0:
            monitor_row = monitor.evaluate(student, epoch=epoch + 1)
            candidate = float(monitor_row["linear_val_macro_f1"])
            if improves_macro_f1(
                candidate,
                best_monitor_score,
                float(monitor_config["minimum_delta_macro_f1"]),
            ):
                best_monitor_score = candidate
                best_epoch = epoch + 1
                _save_final_student(
                    output_dir / "checkpoints" / "best.pt",
                    student=student,
                    config=config,
                    epoch=best_epoch,
                    history=history,
                    selection={
                        "metric": "validation_linear_macro_f1",
                        "value": best_monitor_score,
                        "minimum_delta": float(
                            monitor_config["minimum_delta_macro_f1"]
                        ),
                        "selection_split": "validation",
                        "transductive_ssl": True,
                    },
                )
            print(
                json.dumps(
                    {
                        "monitor": monitor_row,
                        "best_epoch": best_epoch,
                        "best_score": best_monitor_score,
                    },
                    sort_keys=True,
                ),
                flush=True,
            )

    monitor.plot()
    plot_history(
        history,
        ["total", "prediction", "zero_prediction", "regularizer", "variance", "covariance"],
        output_dir / "pretrain_losses.png",
        "B0-Delta pretraining losses",
    )
    plot_history(
        history,
        ["embedding_std"],
        output_dir / "embedding_std.png",
        "B0-Delta student embedding standard deviation",
    )
    plot_history(
        history,
        ["residual_skill", "residual_cosine", "target_delta_rms"],
        output_dir / "residual_diagnostics.png",
        "B0-Delta residual diagnostics",
    )

    raw_best = max(
        monitor.history,
        key=lambda item: (
            float(item["linear_val_macro_f1"]),
            -int(item["epoch"]),
        ),
    )
    final_monitor = monitor.history[-1]
    earlier_scores = [
        float(item["linear_val_macro_f1"])
        for item in monitor.history[:-1]
    ]
    minimum_delta = float(monitor_config["minimum_delta_macro_f1"])
    requires_extension = bool(
        int(final_monitor["epoch"]) == epochs
        and earlier_scores
        and float(final_monitor["linear_val_macro_f1"])
        > max(earlier_scores) + minimum_delta
    )
    duration_selection = {
        "selected_epoch": int(best_epoch),
        "selection_metric": "validation_linear_macro_f1",
        "selection_score": best_monitor_score,
        "raw_best_monitor_epoch": int(raw_best["epoch"]),
        "raw_best_monitor_score": float(raw_best["linear_val_macro_f1"]),
        "horizon_epochs": epochs,
        "requires_extension": requires_extension,
        "extension_rule": (
            "extend only when the final monitored score exceeds every earlier "
            "score by minimum_delta"
        ),
        "minimum_delta_macro_f1": minimum_delta,
        "test_split_used": False,
        "transductive_ssl": True,
        "objective": "teacher_target_minus_teacher_source",
    }
    atomic_json_dump(
        duration_selection,
        output_dir / "duration_selection.json",
    )

    result = {
        "checkpoint": str(output_dir / "checkpoints" / "best.pt"),
        "epochs": epochs,
        "best_epoch": int(best_epoch),
        "best_validation_linear_macro_f1": best_monitor_score,
        "selection_split": "validation",
        "transductive_ssl": True,
        "monitor_epochs": [int(item["epoch"]) for item in monitor.history],
        "total_seconds": time.perf_counter() - run_started,
        "final_metrics": history[-1],
        "duration_selection": duration_selection,
        "objective": {
            "student_input": "more-degraded source image",
            "prediction_target": "EMA_teacher(less-degraded) - EMA_teacher(more-degraded)",
            "target_dtype": "float32 subtraction",
            "all_other_training_settings": "matched to B0 duration pilot",
        },
    }
    atomic_json_dump(result, output_dir / "pretrain_summary.json")
    return result
